Page({
 inputEvent:function(){
   console.log('inputEvent')
 },
 focusEvent:function(){
   console.log('focusEvent')
 },
 blurEvent:function(){
   console.log('blurEvent')
 },
 confirmEvent:function(){
   console.log('confirmEvent')
 }
})
